apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: gcr.io/vschiavo-home/multi-server:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: REDIS_PORT
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: PGUSER
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: PGHOST
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: PGPORT
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: PGDATABASE
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: PGPASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name:  server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port:  5000
      targetPort: 5000
      
